const IMAGE_BASE='https://vmphlzkejnqnvmhygtyv.supabase.co/storage/v1/object/public/faroo-images/';
const poems=[
{mood:'Deep',language:'Hinglish',image:'faroo-deep.jpg',alt:'A quiet reflective scene for deep thoughts',body:`Kuch baatein lafzon tak aayi hi nahi,\nKuch ehsaas dil se jaaye hi nahi.\nHum muskura kar aage badhte rahe,\nPar kuch raaste peeche chhute hi nahi.`},
{mood:'Heartbreak',language:'Hinglish',image:'faroo-heartbreak.jpg',alt:'A cinematic scene of heartbreak and reflection',body:`Kabhi hum bhi kisi ki jaan hua karte the,\nAaj usi ke liye anjaan ho gaye…\nMohabbat toh aaj bhi wahi hai,\nBas hum uski zindagi se nikal gaye.`},
{mood:'Missing You',language:'Hinglish',image:'faroo-missing-you.jpg',alt:'A quiet cinematic scene about missing someone',body:`Tum yaad nahi aate,\nTum toh yaadon mein rehte ho.\nFarq sirf itna hai —\nPehle paas the, ab dil mein ho.`},
{mood:'Love',language:'Hinglish',image:'faroo-love.jpg',alt:'A warm cinematic scene about love',body:`Tera naam likhne ki zaroorat nahi,\nMeri har baat mein tu nazar aata hai.\nIshq shor nahi karta,\nBas har khamoshi mein tera zikr lata hai.`},
{mood:'Alone',language:'English',image:'faroo-alone.jpg',alt:'A solitary cinematic scene at night',body:`Some nights are not lonely\nbecause no one is there.\nThey are lonely because\nthe one you want isn't.`},
{mood:'Memories',language:'Hinglish',image:'faroo-memories.jpg',alt:'A warm nostalgic scene of memories and writing',body:`Waqt guzar gaya,\nPar kuch lamhe wahin reh gaye.\nHum aage badh toh gaye,\nBas dil ke kuch hisse peeche reh gaye.`},
{mood:'Moving On',language:'Hinglish',image:'faroo-moving-on.jpg',alt:'A hopeful cinematic scene about moving forward',body:`Ab tera intezaar nahi karta,\nBas kabhi kabhi yaad aa jaati hai.\nDil ne jaana seekh liya hai —\nHar mohabbat manzil nahi hoti.`}
];
const grid=document.querySelector('#grid'),lang=document.querySelector('#language');let mood='All';
function render(){grid.innerHTML='';const f=poems.filter(p=>(mood==='All'||p.mood===mood)&&(lang.value==='All languages'||p.language===lang.value));f.forEach(p=>{const c=document.createElement('article');c.className='card';c.innerHTML=`<div class="card-visual"><img src="${IMAGE_BASE}${p.image}" alt="${p.alt}" loading="lazy"></div><div class="card-copy"><div><div class="meta">${p.mood} · ${p.language}</div><div class="poem">${p.body}</div></div><div class="actions"><span>FAROO</span><button>Copy</button></div></div>`;c.querySelector('button').onclick=async e=>{await navigator.clipboard.writeText(p.body);e.target.textContent='Copied ✓';setTimeout(()=>e.target.textContent='Copy',1400)};grid.appendChild(c)});if(!f.length)grid.innerHTML='<p>No shayari in this filter yet.</p>'}
document.querySelectorAll('.moods button').forEach(b=>b.onclick=()=>{document.querySelector('.moods .active').classList.remove('active');b.classList.add('active');mood=b.dataset.mood;render();document.querySelector('#shayari').scrollIntoView({behavior:'smooth'})});lang.onchange=render;render();